cmake_minimum_required(VERSION 3.12)

foreach (var IN ITEMS

	BUILD_CUDA_STUBS BUILD_DOCS BUILD_EXAMPLES BUILD_FAT_JAVA_LIB BUILD_IPP_IW
	BUILD_ITT BUILD_JASPER BUILD_JAVA BUILD_JPEG BUILD_OPENEXR BUILD_PACKAGE
	BUILD_PERF_TESTS BUILD_PNG BUILD_PROTOBUF BUILD_SHARED_LIBS BUILD_TBB
	BUILD_TESTS BUILD_TIFF BUILD_USE_SYMLINKS BUILD_WEBP BUILD_WITH_DEBUG_INFO
	BUILD_WITH_DYNAMIC_IPP BUILD_ZLIB

	BUILD_opencv_apps BUILD_opencv_bgsegm BUILD_opencv_bioinspired
	BUILD_opencv_ccalib BUILD_opencv_datasets BUILD_opencv_dnn
	BUILD_opencv_dnn_objdetect BUILD_opencv_dpm BUILD_opencv_face
	BUILD_opencv_flann BUILD_opencv_fuzzy BUILD_opencv_hfs BUILD_opencv_highgui
	BUILD_opencv_img_hash BUILD_opencv_java_bindings_gen BUILD_opencv_js
	BUILD_opencv_line_descriptor BUILD_opencv_ml BUILD_opencv_objdetect
	BUILD_opencv_optflow BUILD_opencv_phase_unwrapping BUILD_opencv_photo
	BUILD_opencv_plot BUILD_opencv_python2 BUILD_opencv_python_bindings_g
	BUILD_opencv_reg BUILD_opencv_rgbd BUILD_opencv_saliency BUILD_opencv_shape
	BUILD_opencv_stereo BUILD_opencv_stitching BUILD_opencv_structured_light
	BUILD_opencv_superres BUILD_opencv_surface_matching BUILD_opencv_text
	BUILD_opencv_tracking BUILD_opencv_ts BUILD_opencv_video
	BUILD_opencv_videostab BUILD_opencv_world BUILD_opencv_xfeatures2d
	BUILD_opencv_ximgproc BUILD_opencv_xobjdetect BUILD_opencv_xphoto

	ENABLE_BUILD_HARDENING ENABLE_CCACHE ENABLE_COVERAGE ENABLE_FAST_MATH
	ENABLE_FLAKE8 ENABLE_GNU_STL_DEBUG ENABLE_IMPL_COLLECTION
	ENABLE_INSTRUMENTATION ENABLE_NOISY_WARNINGS ENABLE_PRECOMPILED_HEADERS
	ENABLE_PROFILING ENABLE_PYLINT ENABLE_SOLUTION_FOLDERS ENABLE_LTO

	INSTALL_CREATE_DISTRIB INSTALL_C_EXAMPLES INSTALL_PYTHON_EXAMPLES
	INSTALL_TESTS

	WITH_1394 WITH_ARAVIS WITH_CLP WITH_CUBLAS WITH_CUDA WITH_CUFFT WITH_EIGEN
	WITH_FFMPEG WITH_GDAL WITH_GDCM WITH_GIGEAPI WITH_GPHOTO2 WITH_GSTREAMER
	WITH_GSTREAMER_0_10 WITH_GTK WITH_GTK_2_X WITH_HALIDE WITH_IMGCODEC_HDR
	WITH_IMGCODEC_PXM WITH_IMGCODEC_SUNRASTER WITH_INF_ENGINE WITH_IPP WITH_ITT
	WITH_JASPER WITH_JPEG WITH_LAPACK WITH_LIBV4L WITH_MATLAB WITH_MFX
	WITH_NVCUVID WITH_OPENCL WITH_OPENCLAMDBLAS WITH_OPENCLAMDFFT
	WITH_OPENCL_SVM WITH_OPENEXR WITH_OPENGL WITH_OPENNI
	WITH_OPENNI2 WITH_OPENVX WITH_PNG WITH_PROTOBUF WITH_PVAPI
	WITH_QT WITH_TBB WITH_TIFF WITH_UNICAP WITH_VA WITH_VA_INTEL
	WITH_VTK WITH_WEBP WITH_XIMEA WITH_XINE WITH_QUIRC WITH_CAROTENE

	)

 set(${var} OFF CACHE BOOL "" FORCE)
endforeach()

# let it autodetect WITH_V4L

foreach (var IN ITEMS

	BUILD_opencv_core BUILD_opencv_aruco BUILD_opencv_calib3d
	BUILD_opencv_features2d BUILD_opencv_imgcodecs BUILD_opencv_imgproc
	BUILD_opencv_videoio

	WITH_PTHREADS_PF WITH_OPENMP

	ENABLE_OMIT_FRAME_POINTER ENABLE_PIC ENABLE_CXX11

	)

 set(${var} ON CACHE BOOL "" FORCE)
endforeach()

set(OPENCV_EXTRA_MODULES_PATH "${CGET_PREFIX}/src/opencv_contrib/modules" CACHE STRING "" FORCE)

include(${CGET_CMAKE_ORIGINAL_SOURCE_FILE})
